import { marked } from 'marked'
import type { LLMSignal } from '@/lib/llm/types'

/**
 * Format a date range for the digest header (e.g. "Mar 17 - Mar 24, 2026").
 */
function formatDateRange(start: Date, end: Date): string {
  const opts: Intl.DateTimeFormatOptions = { month: 'short', day: 'numeric' }
  const startStr = start.toLocaleDateString('en-US', opts)
  const endStr = end.toLocaleDateString('en-US', { ...opts, year: 'numeric' })
  return `${startStr} - ${endStr}`
}

/**
 * Render an array of LLM signals into a Markdown digest document.
 */
export function renderDigest(
  signals: LLMSignal[],
  periodStart: Date,
  periodEnd: Date,
  inputCount: number,
): string {
  const dateRange = formatDateRange(periodStart, periodEnd)
  const sorted = [...signals].sort((a, b) => b.strength - a.strength)

  const lines: string[] = [
    `# Distill Weekly Digest`,
    `**${dateRange}**`,
    '',
    `${signals.length} signals detected from ${inputCount} inputs`,
    '',
  ]

  for (const signal of sorted) {
    lines.push(`## ${signal.statement}`)
    lines.push('')
    lines.push(`**Strength: ${signal.strength}**`)
    lines.push('')
    lines.push(signal.reasoning)
    lines.push('')
    lines.push(`**Evidence:** ${signal.evidence.join(', ')}`)
    lines.push('')
    lines.push(`> **Action:** ${signal.suggested_action}`)
    lines.push('')
    lines.push(signal.themes.map((t) => `\`${t}\``).join(' '))
    lines.push('')
  }

  lines.push('---')
  lines.push(`Generated by Distill on ${new Date().toISOString()}`)

  return lines.join('\n')
}

/**
 * Convert a Markdown digest string to an HTML email body.
 */
export function digestToHtml(markdown: string): string {
  const body = marked.parse(markdown) as string

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1a1a1a; max-width: 680px; margin: 0 auto; padding: 24px; }
  h1 { color: #111; border-bottom: 2px solid #e5e5e5; padding-bottom: 8px; }
  h2 { color: #333; margin-top: 32px; }
  blockquote { border-left: 4px solid #3b82f6; margin: 16px 0; padding: 8px 16px; background: #f0f7ff; }
  code { background: #f3f4f6; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; }
  hr { border: none; border-top: 1px solid #e5e5e5; margin: 32px 0; }
</style>
</head>
<body>
${body}
</body>
</html>`
}
