import { describe, it, expect } from 'vitest'
import { renderDigest, digestToHtml } from '@/lib/digest'
import type { LLMSignal } from '@/lib/llm/types'

const mockSignals: LLMSignal[] = [
  {
    statement: 'Users want dark mode',
    reasoning: 'Multiple users requested a dark theme for better accessibility.',
    evidence: ['input-1', 'input-3'],
    suggested_action: 'Add dark mode toggle to settings',
    themes: ['ui', 'accessibility'],
    strength: 3,
  },
  {
    statement: 'Login performance is degrading',
    reasoning: 'Several bug reports about slow login times.',
    evidence: ['input-2', 'input-4', 'input-5'],
    suggested_action: 'Profile and optimize auth flow',
    themes: ['performance', 'auth'],
    strength: 5,
  },
]

describe('renderDigest', () => {
  const periodStart = new Date('2026-03-17T09:00:00Z')
  const periodEnd = new Date('2026-03-24T09:00:00Z')

  it('produces Markdown with header and date range', () => {
    const md = renderDigest(mockSignals, periodStart, periodEnd, 10)

    expect(md).toContain('# Distill Weekly Digest')
    expect(md).toContain('Mar 17')
    expect(md).toContain('Mar 24')
  })

  it('includes signal count and input count summary', () => {
    const md = renderDigest(mockSignals, periodStart, periodEnd, 10)

    expect(md).toContain('2 signals detected from 10 inputs')
  })

  it('renders each signal with statement as h2', () => {
    const md = renderDigest(mockSignals, periodStart, periodEnd, 10)

    expect(md).toContain('## Users want dark mode')
    expect(md).toContain('## Login performance is degrading')
  })

  it('includes strength, reasoning, evidence, action, and themes', () => {
    const md = renderDigest(mockSignals, periodStart, periodEnd, 10)

    expect(md).toContain('**Strength: 5**')
    expect(md).toContain('**Strength: 3**')
    expect(md).toContain('Multiple users requested a dark theme')
    expect(md).toContain('**Evidence:** input-1, input-3')
    expect(md).toContain('> **Action:** Add dark mode toggle to settings')
    expect(md).toContain('`ui`')
    expect(md).toContain('`accessibility`')
  })

  it('sorts signals by strength descending', () => {
    const md = renderDigest(mockSignals, periodStart, periodEnd, 10)

    const loginPos = md.indexOf('## Login performance is degrading')
    const darkModePos = md.indexOf('## Users want dark mode')
    // strength 5 should appear before strength 3
    expect(loginPos).toBeLessThan(darkModePos)
  })

  it('includes footer with generation date', () => {
    const md = renderDigest(mockSignals, periodStart, periodEnd, 10)

    expect(md).toContain('---')
    expect(md).toContain('Generated by Distill on')
  })

  it('handles empty signals array', () => {
    const md = renderDigest([], periodStart, periodEnd, 0)

    expect(md).toContain('# Distill Weekly Digest')
    expect(md).toContain('0 signals detected from 0 inputs')
    // No signal headings
    expect(md).not.toContain('## ')
  })
})

describe('digestToHtml', () => {
  it('converts Markdown to HTML with h1 and h2 tags', () => {
    const md = renderDigest(mockSignals, new Date('2026-03-17T09:00:00Z'), new Date('2026-03-24T09:00:00Z'), 10)
    const html = digestToHtml(md)

    expect(html).toContain('<h1>')
    expect(html).toContain('<h2>')
  })

  it('wraps output in HTML email wrapper', () => {
    const html = digestToHtml('# Test')

    expect(html).toContain('<!DOCTYPE html>')
    expect(html).toContain('<html>')
    expect(html).toContain('</html>')
    expect(html).toContain('<body>')
    expect(html).toContain('</body>')
  })

  it('includes inline styles for email readability', () => {
    const html = digestToHtml('# Test')

    expect(html).toContain('font-family')
    expect(html).toContain('max-width')
  })
})
